### ISSUE TITLE
Portable PDB + NullGuard breaks breakpoints

### ISSUE THREAD

**Issue by SirUppyPancakes** [Fody/NullGuard#90] opened 2017-11-13 19:16 UTC
When using a NETStandard 2.0 library with NullGuard 1.6.2, breakpoints are not hit with the message: "The breakpoint will not currently be hit. No executable code of the debugger's target code type is associated with this line...".

I have attached a VS-2017 solution that reproduces the issue. Simply place a breakpoint anywhere in the "Test" method of "Class1" and debug "ConsoleApp1".
[ConsoleApp1.zip](https://github.com/Fody/NullGuard/files/1468154/ConsoleApp1.zip)

**Comment by SimonCropp** [comment] 2017-11-14 01:22
can u update to fody 2.2.1 and see if the problem still exists

**Comment by SirUppyPancakes** [comment] 2017-11-14 02:18
Yep, if I add Fody 2.2.1 to the projects, the problem persists (commenting out the NullGuard line in the weavers XML file makes it go away).
[ConsoleApp1_Fody_2_2_1.zip](https://github.com/Fody/NullGuard/files/1469365/ConsoleApp1_Fody_2_2_1.zip)

**Comment by SimonCropp** [comment] 2017-12-19 11:50
does the behaviour differ between debug and release. and can u verify that in v 2.3.2 of fody?

**Comment by SirUppyPancakes** [comment] 2017-12-20 01:47
The issue is still present in the latest build of Visual Studio 2017 (15.5.2), NullGuard 1.6.3, and Fody 2.3.2.
Also, I'm not sure what you mean by comparing Debug/Release since Release already causes breakpoints to be missed with its default configuration. As expected, the breakpoints are still missed in Release (but so are any breakpoints in the Program.cs class as well).

[ConsoleApp1_Fody_2_3_2.zip](https://github.com/Fody/NullGuard/files/1573875/ConsoleApp1_Fody_2_3_2.zip)

**Comment by Leon99** [comment] 2018-03-05 05:53
The same here. .Net Standard 2.0, NullGuard.Fody 1.7.1, Fody 2.4.1 - as long as NullGuard is enabled, breakpoints won't work.

**Comment by Leon99** [comment] 2018-03-09 02:05
@Remedij I'll give it a try, thank you. Is there elaboration somewhere on why the portable option doesn't work and/or whether there are any plans to support it eventually?

**Comment by SimonCropp** [comment] 2018-03-09 03:48
my guess would be a bug in cecil (cc @jbevain). the portable support in cecil is relatively new and some qwerks would not surprise me.

**Comment by jbevain** [comment] 2018-03-09 17:50
Either that or https://github.com/Fody/NullGuard/blob/b8415d9db020b7485db4dc99d9ae659ae4123c3f/NullGuard.Fody/SymbolExtensions.cs#L12 is doing something weird and creating a set of sequence points that are not understood by the portable pdb support in the debugger.

**Comment by cybervoodoo** [comment] 2018-07-03 08:06
Same issue with NullGuard 1.8.0 (Fody 3.1.3)  in Netstandard 2.0 library

**Comment by SlowLogicBoy** [comment] 2018-07-23 08:40
I have the same issue on VSCode (using `"type": "clr"` debugger).

I can hit methods that are not affected by NullGuard by stepping in, however I can't hit methods modified by NullGuard at all.
I've tried:
```xml
<DebugType>Portable</DebugType>
```
and
```xml
<DebugType>Full</DebugType>
```
(because that sometimes helps with other weavers, and when referencing netstandard from netfx projects)
FodyWeavers.xml:
```xml
<?xml version="1.0" encoding="utf-8" ?>
<Weavers>
  <NullGuard Mode="Implicit" />
  <PropertyChanged />
  <AutoDI />
</Weavers>
```
When I disable `NullGuard` everything works as expected (with `<DebugType>Portable</DebugType>`)

**Comment by SimonCropp** [comment] 2018-08-30 12:27
closing this as stale. if it is still an problem please raise a new issue

**Comment by ulrichb** [comment] 2018-08-30 12:46
@SimonCropp 

Stop. Closing. Unfixed. Bugs.

That's not funny. 

I'll said it the last time (#84) and will keep telling.

Don't mess with your user base by making bugs less visible / discoverable. It's okay to wait a long time for a fix PR. But it's not okay to just ignore them.

Please reopen this and all the other unfixed bugs.

**Comment by SimonCropp** [comment] 2018-08-30 12:56
@ulrichb in theory i agree with you. but leaving around issues for years, with no one working on them, just means it is more difficult to keep the project moving forward. and, arguably, if no one cares enough to actually fix an issue, it is not important enough to be fixed. also people can still discover these issues even if they are closed. 

currently i maintain 128 nugets https://www.nuget.org/profiles/simoncropp, and i am really struggling to triage the work load. so i want to try closing stale issues and see if that has a net positive effect on the projects i maintain

Note that i am not the first to start doing this 

 * https://github.com/Catel/Catel.Fody/issues/18#issuecomment-393731232
 * https://github.com/probot/stale#is-closing-stale-issues-really-a-good-idea
 * https://github.com/reactiveui/ReactiveUI/blob/master/.github/stale.yml#L24

**Comment by SimonCropp** [comment] 2018-08-30 13:02
@ulrichb happy to transfer ownership of this project to you if think you have more capacity to triage these old issues

**Comment by ghuntley** [comment] 2018-08-30 13:04
Closing stale issues may seem inhospitable or offensive but the alternative is to disrespect you by setting false expectations and implicitly ignoring your work. Automatically closing issues makes it explicit: if work is not progressing, then it's stale. A comment is all it takes to keep the conversation alive.

**Comment by ulrichb** [comment] 2018-08-30 13:31
First, big thanks for your great work on Fody and all the other OSS stuff!

I fear we won't agree on this topic. I just see no advantage on *closing* them. Why not adding a tag? Something like _"no time - waiting for the community"_. IMO this would be much better and you could use a "-label:XXX" filter to solve the problem on having too much noise on the issues list.

> if no one cares enough to actually fix an issue, it is not important enough to be fixed

First, there is also the possibility that people simply don't understand the underlying problem and aren't able to fix it. Second, "important enough to be fixed" != "not existent" => no reason to close it. Also here you can use tags like _"minor issue - waiting for somebody to fix that if it really hurts her/him"_.

I didn't know that other OSS projects do this too (and even automate it 🤦‍♂️ ). I hope that this doesn't become a standard.

Regarding ownership: Two years ago (where I also contributed a few things) I would have loved to do this. Atm. I use NullGuard only (very passively as part of my system under test) in [ImplicitNullability](https://github.com/ulrichb/ImplicitNullability/). Therefore I would be a very bad maintainer. Maybe later, when I do more C# again.

**Comment by matkoch** [comment] 2018-08-30 14:06
@SimonCropp @ghuntley  I'm sorry, but I really don't see how closing issues is helping to move a project forward. Neither do I see how leaving them open sets wrong expectations. Like @ulrichb  already pointed out, this is about discoverability. And why exactly do you want people to open a new issue, instead of reopening the existing one?

Closing issues as stale might be a good idea for feature requests, because projects evolve, and there might be another solution, or the user came up with something on their own. But closing _bug reports_ is really pointless from my point of view.

**Comment by matkoch** [comment] 2018-08-30 14:12
Btw, how is this issue even stale? Last activity was just a month ago.

**Comment by j2jensen** [comment] 2018-08-30 15:45
Since you used ReactiveUI as an example, I'd like to point out a few things:

1. They mark an issue as stale after 60 days. People have a week to respond. If they do, the issue is left open. They also have a whitelist of issue tags that will never be marked stale. [source](https://github.com/reactiveui/ReactiveUI/blob/master/.github/stale.yml)
2. They currently have 89 Open Issues and 748 Closed. Of those, 18 of the Open cases have been marked as stale and 31 of the Closed cases were marked as stale at some point before they were closed. [source](https://github.com/reactiveui/ReactiveUI/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+%22marked+as+stale%22) 

I totally understand why it makes sense to automate the closing of stale issues. There are plenty of cases where someone posts an issue that cannot be reproduced, and they never respond to follow-up questions. And since no activity is happening, these are the issues least likely to draw the attention of people actually working on the project. I think if you follow a pattern similar to ReactiveUI's, you're unlikely to get much push-back. And it looks like they're using a [stale bot](https://github.com/apps/stale) that should be very easy to apply.

What's happened here, instead, is that there are zero open issues on this project, and 70 Closed issues. Someone looking at using this library is going to assume this means that you're staying on top of all the issues, and that NullGuard is very stable. They will then re-discover an issue like this (which is a big deal for us, and is preventing us from using NullGuard on several new projects), Google it, find a Closed issue, read down the comments to figure out if it was closed because it got fixed or if they are somehow using it the wrong way, and finally discover that it's actually still an outstanding issue. They will be tempted to create a new issue, as you suggest, until [they see](https://github.com/Fody/NullGuard/issues/new) all that will be expected of them to open a new issue. They'll also consider how the issue is likely to get closed again without getting fixed, and decide it's probably not even worth the effort to report it. And the cycle will repeat with everyone who tries using NullGuard on a new project.

Meanwhile, there will be no visibility into the fact that issues exist, or how many people are affected by the issues, and therefore no way for a contributor to decide what should be prioritized. Even if someone took the time to create a new issue, the fact that it's fragmented means you won't be able to see how much interest the issue has generated _on the whole_ compared to other issues.

So here's what I would ask:
1. Re-open this issue specifically because it's clear that it's not stale, and affecting a lot of people. Reopening it will be more beneficial than creating a new duplicate of it.
2. Install the stale bot and decide on some sane thresholds and rules to apply so you automatically get the benefits you're looking for without raising the ire of the community.

If you'd like I can create a pull request with a stale.yml file in it. I could also create a new issue to track it. If you want to give me the appropriate permissions I'd be willing to add the stalebot app.

In the past, I have tried digging into the code and figuring out how to fix issues with Fody add-ins, but I have no experience with IL generation and found it to be beyond my ken. The spirit is willing but the mind is weak. ;-)

**Comment by ulrichb** [comment] 2018-08-30 19:09
@j2jensen Very good and detailed write-up.

+1 for 70 closed/0 open issues is a distorted view of the actual stability of NullGuard for people who consider employing it (e.g. this is one of the things I personally take into account when choosing a new dependency).

+1 for closing bugs which are *both* not-reproducible _and_ the reporter doesn't react within, let's say, two months. I have no problem with that. Such kind of bugs can/should be closed with a "not reproducible" tag. But that's not the case here or in #84. 

One more thing (taking #84 again as an example): When just reading the title / the reporter's description + the fact that it's closed (without any label) clearly speaks "this bug has been fixed". Which isn't true. So the _absolute minimum_ would be to tag it clearly as "closed because stale" (like the "closed / won't fix" state in a bug tracker). It shouldn't be necessary to read down to the end of the conversation.

**Comment by SimonCropp** [comment] 2018-08-30 19:46
Given enough people think this issue is important/critical enough to remain open i will re-open this.

However given it is unlikely to be fixed any time soon, and it is critical, i think the best course of action would be to mark this repo and nuget as "do not use". by this i mean adding to the nuget and the top of the readme the text

> This project has a critical but that has not been fixed. link. only use this project if the bug does not effect you, or alternatively submit a pull request that fixes the bug.  


### on closing stale issues

Closing stale issues does not imply they cannot be re-opened, as i have done here.

I admit i was perhaps to over zealous in some of the issues i closed. but i figured calling issue bankruptcy, and cleaning the back log, was better than marking the majority of my projects as abandoned and ignored.  

@ulrichb 

> IMO this would be much better and you could use a "-label:XXX" filter to solve the problem on having too much noise on the issues list.

If i was managing a small number of projects i can see this helping mitigate the signal to noise. but currently i have [36 fody project](https://github.com/Fody), [18 NServiceBus projects](https://github.com/NServiceBusExtensions/), [16 active projects under my account](https://github.com/SimonCropp?tab=repositories), and probably another 5 i contribute to heavily. moving between the various mechanisms of managing a repo (octokit, email, github etc), and the differences/inconsistencies in how projects are managed means labels is not a viable way forward 

> When just reading the title / the reporter's description + the fact that it's closed (without any label) clearly speaks "this bug has been fixed"

I dont think this is the case. only issues that are closed and have a milestone should be considered fixed. should i add that to the readme

I could add a label. but the actual status "closed because no one thought it important enough to put the effort in to fixing it" seems a little verbose

@j2jensen 

> If you'd like I can create a pull request with a stale.yml file in it. I could also create a new issue to track it. If you want to give me the appropriate permissions I'd be willing to add the stalebot app.

i have installed stalebot, and will be tweaking its settings over the next few weeks. thanks for the offer of help

> What's happened here, instead, is that there are zero open issues on this project, and 70 Closed issues. Someone looking at using this library is going to assume this means that you're staying on top of all the issues, and that NullGuard is very stable.....

i can see "how to choose an active project" as being difficult. i would postulate that "number of open issues is a poor measure. look at nullguard, this single issue is probably enough that people should avoid using it. so to get a "picture of repo from open issues" you would need to read every issue and judge the criticality of every issue.

My approach to picking projects to use is as follows:

review the code base. if it is poor quality the perhaps avoid. if it is too complex for me to understand, then that is problematic. since if i do find a bug or want a feature it is not possible for me to submit a PR. this is a risk and you need to consider how to mitigate it. you dont want to be in a situation where you are running a production codebase on a tool that you cannot fix and are relying on people to spend their free time to fix it for you. consider assigning someone on your team to spend the time to get up to speed. perhaps approach one of the community members to enter into a support agreement

if u want to measure the responsiveness of a project, consider submitting a basic cleanup PR. add some doco, fix some spelling etc. how well that interaction proceeds will tell you much about the project.

look for abandoned PRs

does the project have adequate tests and an automated CI to verify them.

**Comment by matkoch** [comment] 2018-08-30 20:06
That was a rather quick journey from making issues hard to discover to marking the package as better not to use.

**Comment by tom-englert** [comment] 2018-09-01 14:17
@SimonCropp I could help to triage the issues for this project if you don't mind. (or for other Fody projects too)

**Comment by SimonCropp** [comment] 2018-09-01 22:35
@tom-englert sure. I appreciate anyhelp

**Comment by tom-englert** [comment] 2018-09-02 16:07
@jbevain I have just tried to reproduce this. This is independent of the target framework, so the issue should not name "NETStandard 2.0 library" but "Portable PDBs" as the root cause. 
When using "DebugType full" everything works fine. 
Looking at the output with "JetBrains dotPeek" with "DebugType full" shows that all sequence points are there and fine.
After switching to "DebugType portable", dotPeek can't read the pdb at all and does not show the original source but a decompiled version.
Disabling the "UpdateDebugInfo" method that you have mentioned does not change anything.
Since the Fody code is agnostic of the kind of pdb's used, and works fine with full pdbs, I can't imagine what is going wrong here.
Is there anything special that needs to be considered when using Cecil with portable pdbs?

**Comment by j2jensen** [comment] 2018-09-02 16:27
@SimonCropp I just want to take a moment to thank you for your well-thought-out and carefully considered response. Thank you for taking the criticism here in the spirit in which it was intended, explaining where you're coming from, and understanding where we're coming from. You make some very excellent points, which I will take to heart.

**Comment by tom-englert** [comment] 2018-09-04 17:55
@SimonCropp I think I've found it, maybe you can have a short review: https://github.com/Fody/NullGuard/tree/issue%2390

**Comment by SimonCropp** [comment] 2018-09-04 23:28
@tom-englert nice work. looks good to me

**Closed** 2018-09-07 06:48 UTC
Labels: bug

**Comment by SimonCropp** [comment] 2018-09-08 10:28
I tend to prefer pointing people to milestones over duplicating the information in release notes

**Comment by SimonCropp** [comment] 2018-09-08 10:36
They dont need to track through commits. Issues can be assigned to a milestone

**Comment by tom-englert** [comment] 2018-09-08 10:45
Yes, but you don't see them in the history. 
However, it was just an offer to contribute something that was already requested by the community and would make it more transparent.

**Comment by SimonCropp** [comment] 2018-09-08 11:37
> Yes, but you don't see them in the history.

what do you mean by this?

**Comment by tom-englert** [comment] 2018-09-08 13:40
if you browse through the history of commits, you cannot see milestones.

**Comment by tom-englert** [comment] 2018-09-08 13:45
however no need to discuss this in detail - if you don't see any benefit in it, I can live with how it's now.
If you don't mind, I can continue maintaining tags, milestones and releases for this project.
